# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: SSH to Google Cloud Platform compute instances
author: Google LLC
description: |-
  Use this action to connect to Google Cloud Platform instances via ssh and execute user's commands.

inputs:
  instance_name:
    description: |-
      Name of the virtual machine instance to SSH into.
    required: true

  zone:
    description: |-
      Zone of the instance to connect to.
    required: true

  user:
    description: |-
      Specifies the username with which to SSH. 
      If omitted, the user login name is used. If using OS Login, USER will be replaced by the OS Login user.
    required: false

  ssh_private_key:
    description: |-
      SSH private key with which to SSH.
    required: true

  ssh_public_key:
    description: |-
      SSH public key with which to SSH.
    required: true

  ssh_keys_dir:
    description: |-
      Path for a directory to store ssh keys
    required: false

  container:
    description: |-
      The name or ID of a container inside of the virtual machine instance to connect to.
      This only applies to virtual machines that are using a Google Container-Optimized 
      virtual machine image.
    required: false

  ssh_args:
    description: |-
      Additional flags to be passed to ssh tool. Example: '-vvv -L 80:%INSTANCE%:80'.
    required: false

  command:
    description: |-
      A command to run on the virtual machine.
      Action runs the command on the target instance and then exits.
    required: false

  script:
    description: |-
      A path for a bash script to run on the virtual machine.
      Action runs the file on the target instance and then exits.
    required: false

  project_id:
    description: The GCP project ID. Overrides project ID set by credentials.
    required: false

  flags:
    description: |-
      Space separated list of other compute ssh flags, examples can be found:
      https://cloud.google.com/sdk/gcloud/reference/compute/ssh/#FLAGS. Ex 
      --ssh-key-expiration=2017-08-29T18:52:51.142Z.
    required: false

  gcloud_version:
    description: |-
      Version of the Cloud SDK to install. If unspecified or set to "latest",
      the latest available gcloud SDK version for the target platform will be
      installed. Example: "290.0.1".
    required: false

outputs:
  stdout:
    description: stdout from ssh command
  stderr:
    description: stderr from ssh command

runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
